### ISSUE TITLE
Hardcoded .pem file location in pools.py

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#1]
pools.py contains a hardcoded reference to /Users/pazcal when a search is made for a .pem file. This should be replaced by one to xbow.XBOW_CONFIGDIR

**Comment by CharlieLaughton** [comment]
Bugfix uploaded to level branch. Please check

**Comment by CharlieLaughton** [comment]
@ChrisSuess : can you confirm this fix works for you (that you can launch a cluster)? I think this is for sure, but just for completeness, and I will close the issue.

**Comment by ChrisSuess** [comment]
Fix works and cluster can be launched. Issue will be closed
