### ISSUE TITLE
Filesystem does not remount if the head node is rebooted

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#10]
If you reboot the head node everything falls apart, as the /shared filesystem does not automatically remount. As a result the task scheduler cannot find the dsf.json file.

**Comment by ChrisSuess** [comment]
This needs a mount command added to fstab at the when the cluster is launched. This can be added to the user data that the VM receives when booting.

**Comment by ChrisSuess** [comment]
This has been addressed and fixed in the commit 4ddca47.
