### ISSUE TITLE
New file systems do not have a visible name

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#11]
If you create a new filesystem, its name is defined in the 'CreationToken' variable, but this does not appear on the EC2 console display. If a tag with the name 'Name' is set to the same value, this fixes it.

I have done this manually for existing filesystems, but needs to be fixed in the code.

Not strictly a bug as the system still works, but rather confusing to a user.

**Comment by ChrisSuess** [comment]
Agreed. Commit 686967b fixes this issue and adds a tag to when creating filesystem
