### ISSUE TITLE
Cuda upgrade in AMI

### ISSUE THREAD

**Issue by ChrisSuess** [ChrisSuess/Project-Xbow#16]
Newer GPU instances (P3's) need Cuda 8.0+ to run pmemd.cuda.

Gives the error:

`cudaMemcpyToSymbol: SetSim copy to cSim failed invalid device symbol`

**Comment by ChrisSuess** [comment]
according to Ambers site on GPU's Amber18 supports:

> Volta (V100 - SM_70) based cards require CUDA 9.0 or later.

AWS p3 instances use the V100 GPU so need CUDA 9.0+. I have upgraded the CUDA version on a p3 instances but this still did not fix the issue. I suspect that it may need a CUDA upgrade to 9.0+ and also Amber may need recompiling and/or upgrading to Amber18. @CharlieLaughton Can we do this and will it mess with everything else that is working fine? 

    `sudo dpkg -i cuda-repo-ubuntu1604_9.2.88-1_amd64.deb`
    `sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub`
    `sudo apt-get update`
    `sudo apt-get install cuda`

deb can be downloaded from 

`https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1604&target_type=debnetwork`

**Comment by CharlieLaughton** [comment]
I'm not sure that this issue should be tagged as an enhancement, as we will never be able to distribute AMIs with Amber18 for licensing reasons. What would be more relevant would be to have a page on the Wiki or similar that explains how a user can build their own private AMBER-18 powered AMI (or any xbow/xflow-compliant image, for that matter).
