### ISSUE TITLE
More automation in xbow-config

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#2]
All xbow-config does at present is create the .pem files for the head node and the workers. A new user has to do lots of other things manually before they can use xbow, including:

1. Ensuring $HOME/.aws exists and contains credentials and config file (which defines the default region)
2. Creating the security groups 'efs-walkthrough1-mt-sg' and 'efs-walkthrough1-ec2-sg'.

It would be great if these could be automated.

**Comment by CharlieLaughton** [comment]
I have added some notes about what a new user needs to do on the wiki:
https://github.com/ChrisSuess/Project-Xbow/wiki

**Comment by ChrisSuess** [comment]
This is now available xbow-config
