### ISSUE TITLE
xbow-submit gmx mdrun uploads all files to cluster

### ISSUE THREAD

**Issue by athina1** [ChrisSuess/Project-Xbow#24]
When running 'xbow-submit gmx mdrun -deffnm input_name', all files in current directory get uploaded on the cluster, not only the specified run input file

**Comment by ChrisSuess** [comment]
The way we like to think of the problem is self contained folders hence we transfer all the necessary files. Granted this can be slightly cumbersome but we are still working on an elegant way to transfer specific files.
