### ISSUE TITLE
xbow-config fails if $HOME/.xbow does not already exist

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#3]
If a new user runs xbow-config, it fails unless .xbow already exists.

**Comment by CharlieLaughton** [comment]
Bugfix uploaded to devel branch, please check.

**Comment by CharlieLaughton** [comment]
@ChrisSuess : For independent verification, can you please confirm this fix solves the issue?

**Comment by ChrisSuess** [comment]
Fix worked fine when I tested it as well. Will close the issue
