### ISSUE TITLE
xbow-create_cluster fails for fresh install

### ISSUE THREAD

**Issue by CharlieLaughton** [ChrisSuess/Project-Xbow#9]
xbow-create_clusterfails on a fresh install. Running xbow-configure creates the settings.yml file but that's all, so then:
```
Starting the scheduler node - this may take some time...
Traceback (most recent call last):
  File "/Users/pazcal/miniconda3/envs/py27/bin/xbow-create_cluster", line 36, in <module>
    user_data=user_data
  File "/Users/pazcal/miniconda3/envs/py27/lib/python2.7/site-packages/xbow/instances.py", line 309, in create
    raise RuntimeError('Error - cannot find {}'.format(pem_file))
RuntimeError: Error - cannot find /Users/pazcal/.xbow/MyScheduler.pem
(py27) Charless-MacBook-Pro:.xbow pazcal$ 
```

**Comment by ChrisSuess** [comment]
When `xbow-configure` runs it creates the .pem files based on scheduler_name and worker_pool_name in the settings.yml. If the names of .pem file are already attached to your amazon account it doesn't create new ones unless you give it `-f` flag (not documented) which I have changed to default now.

I am currently working on adding user defined values when running the `xbow-configure` command to avoid this.

**Comment by ChrisSuess** [comment]
I have updated pip repo as well should give `xbow 0.3.5`

`pip install xbow --upgrade`
